serial_no: ''
json_file_path: ''
camera: camera
tf_prefix: camera
external_manager: false
manager: realsense2_camera_manager
fisheye_width: 640
fisheye_height: 480
enable_fisheye: true
depth_width: 640
depth_height: 480
enable_depth: true
infra_width: 640
infra_height: 480
enable_infra1: true
enable_infra2: true
color_width: 640
color_height: 480
enable_color: true
fisheye_fps: 30
depth_fps: 30
infra_fps: 30
color_fps: 30
gyro_fps: 400
accel_fps: 250
enable_gyro: true
enable_accel: true
enable_pointcloud: false
pointcloud_texture_stream: RS2_STREAM_COLOR
pointcloud_texture_index: 0
enable_sync: false
align_depth: false
publish_tf: true
tf_publish_rate: 0
clip_distance: -2
filters: ''
linear_accel_cov: 0.01
initial_reset: false
unite_imu_method: ''
topic_odom_in: odom_in
calib_odom_file: ''
publish_odom_tf: true
allow_no_texture_points: false
